### ISSUE TITLE
not support tensorflow-gpu version?

### ISSUE THREAD

**Issue by plutoyuxie** [mpatacchiola/deepgaze#76]
Hi, thanks for the repo. I meet an error when runing the example code of ex_cnn_head_pose_estimation_images.py. 
It seems the error occurs with tensorflow-gpu, when I change to tensorflow==1.5 with python 2.7 (same as you have mentioned) it works well.
Belows is the record, thanks for help.

Processing image ..... 1.jpg
2019-06-25 17:06:17.044046: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-06-25 17:06:29.808930: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-06-25 17:06:29.831308: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/user/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/user/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node Conv2D}}]]

**Comment by mpatacchiola** [comment]
Hi @plutoyuxie 

> It seems the error occurs with tensorflow-gpu, when I change to tensorflow==1.5 with python 2.7 (same as you have mentioned) it works well.

I did not understand when it is working and when it is not working. There are a few possibilities that led to the issue. One can be that the version of cuDNN you have on your system is not compatible with tensorflow 1.5. It is pretty annoying but specific versions of tensorflow require specific versions of cuDNN.

**Comment by plutoyuxie** [comment]
Thanks.
